In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv("odev_tenis.csv.opdownload")
veriler.head()


outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [4]:
play = veriler.iloc[:,-1:].values


In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
play[:,-1] = le.fit_transform(veriler.iloc[:,-1])
print(play)
veriler["play"] = play
veriler.head()

[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


outlook  temperature  humidity  windy play
0     sunny           85        85  False    0
1     sunny           80        90   True    0
2  overcast           83        86  False    1
3     rainy           70        96  False    1
4     rainy           68        80  False    1

In [10]:
windy = veriler.iloc[:,-2:-1].values
windy[:,-1] = le.fit_transform(veriler.iloc[:,-1])
print(windy)

[[False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]]


In [11]:
veriler = pd.read_csv("odev_tenis.csv.opdownload")

In [17]:
veriler2 = veriler.apply(preprocessing.LabelEncoder().fit_transform)
c = veriler2.iloc[:,:1]
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)
veriler2.head()

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


outlook  temperature  humidity  windy  play
0        2           11         4      0     0
1        2            8         6      1     0
2        0           10         5      0     1
3        1            4         9      0     1
4        1            2         3      0     1

In [20]:
hava_durumu = pd.DataFrame(data = c, index = range(14), columns = ["o","r","s"])
son_veriler = pd.concat([hava_durumu,veriler.iloc[:,1:3]],axis = 1)
son_veriler.head()

o    r    s  temperature  humidity
0  0.0  0.0  1.0           85        85
1  0.0  0.0  1.0           80        90
2  1.0  0.0  0.0           83        86
3  0.0  1.0  0.0           70        96
4  0.0  1.0  0.0           68        80

In [21]:
son_veriler = pd.concat([son_veriler,veriler2.iloc[:-2:]],axis = 1)
son_veriler.head()

o    r    s  temperature  humidity  outlook  temperature  humidity  \
0  0.0  0.0  1.0           85        85      2.0         11.0       4.0   
1  0.0  0.0  1.0           80        90      2.0          8.0       6.0   
2  1.0  0.0  0.0           83        86      0.0         10.0       5.0   
3  0.0  1.0  0.0           70        96      1.0          4.0       9.0   
4  0.0  1.0  0.0           68        80      1.0          2.0       3.0   

   windy  play  
0    0.0   0.0  
1    1.0   0.0  
2    0.0   1.0  
3    0.0   1.0  
4    0.0   1.0

In [7]:
from sklearn import preprocessing
veriler = pd.read_csv("odev_tenis.csv.opdownload")
veriler2 = veriler.apply(preprocessing.LabelEncoder().fit_transform)
c = veriler2.iloc[:,:1]
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
hava_durumu = pd.DataFrame(data = c, index = range(14), columns = ["o","r","s"])
son_veriler = pd.concat([hava_durumu,veriler.iloc[:,1:3]],axis = 1)
son_veriler = pd.concat([son_veriler,veriler2.iloc[:-2:]],axis = 1)
son_veriler.head()

o    r    s  temperature  humidity  outlook  temperature  humidity  \
0  0.0  0.0  1.0           85        85      2.0         11.0       4.0   
1  0.0  0.0  1.0           80        90      2.0          8.0       6.0   
2  1.0  0.0  0.0           83        86      0.0         10.0       5.0   
3  0.0  1.0  0.0           70        96      1.0          4.0       9.0   
4  0.0  1.0  0.0           68        80      1.0          2.0       3.0   

   windy  play  
0    0.0   0.0  
1    1.0   0.0  
2    0.0   1.0  
3    0.0   1.0  
4    0.0   1.0

In [8]:


son_veriler.head()

o    r    s  temperature  humidity  outlook  temperature  humidity  \
0  0.0  0.0  1.0           85        85      2.0         11.0       4.0   
1  0.0  0.0  1.0           80        90      2.0          8.0       6.0   
2  1.0  0.0  0.0           83        86      0.0         10.0       5.0   
3  0.0  1.0  0.0           70        96      1.0          4.0       9.0   
4  0.0  1.0  0.0           68        80      1.0          2.0       3.0   

   windy  play  
0    0.0   0.0  
1    1.0   0.0  
2    0.0   1.0  
3    0.0   1.0  
4    0.0   1.0

In [11]:
son_veriler2 = son_veriler.iloc[:,0:5]

In [13]:
son_veriler2.head()

o    r    s  temperature  humidity
0  0.0  0.0  1.0           85        85
1  0.0  0.0  1.0           80        90
2  1.0  0.0  0.0           83        86
3  0.0  1.0  0.0           70        96
4  0.0  1.0  0.0           68        80

In [14]:
son_veriler3 = son_veriler.iloc[:,-2:]
son_veriler3.head()

windy  play
0    0.0   0.0
1    1.0   0.0
2    0.0   1.0
3    0.0   1.0
4    0.0   1.0

In [28]:
son_veriler = pd.concat([son_veriler3,son_veriler2], axis = 1)


son_veriler["windy"][13] = 1
son_veriler["play"][13] = 0
son_veriler["windy"][12] = 0
son_veriler["play"][12] = 1
son_veriler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   windy        14 non-null     float64
 1   play         14 non-null     float64
 2   o            14 non-null     float64
 3   r            14 non-null     float64
 4   s            14 non-null     float64
 5   temperature  14 non-null     int64  
 6   humidity     14 non-null     int64  
dtypes: float64(5), int64(2)
memory usage: 912.0 bytes


<ipython-input-28-c26316362098>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  son_veriler["windy"][13] = 1
<ipython-input-28-c26316362098>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  son_veriler["play"][13] = 0
<ipython-input-28-c26316362098>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  son_veriler["windy"][12] = 0
<ipython-input-28-c26316362098>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice f

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(son_veriler.iloc[:,:-1],son_veriler.iloc[:,-1:], test_size = 0.33, random_state=0)


In [30]:
x_train

windy  play    o    r    s  temperature
13    1.0   0.0  0.0  1.0  0.0           71
9     0.0   1.0  0.0  1.0  0.0           75
1     1.0   0.0  0.0  0.0  1.0           80
7     0.0   0.0  0.0  0.0  1.0           72
10    1.0   1.0  0.0  0.0  1.0           75
3     0.0   1.0  0.0  1.0  0.0           70
0     0.0   0.0  0.0  0.0  1.0           85
5     1.0   0.0  0.0  1.0  0.0           65
12    0.0   1.0  1.0  0.0  0.0           81

In [31]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86

In [32]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)


In [36]:
import statsmodels.api as sm
X = np.append(arr = np.ones((14,1)).astype(int), values = son_veriler.iloc[:,:-1],axis = 1)
X_l = son_veriler.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(son_veriler.iloc[:,-1:],X_l).fit()
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Mon, 25 Jul 2022   Prob (F-statistic):              0.661
Time:                        10:20:07   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.5

C:\Users\fatih\anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [37]:
son_veriler = son_veriler.iloc[:,1:]

In [38]:
import statsmodels.api as sm
X = np.append(arr = np.ones((14,1)).astype(int), values = son_veriler.iloc[:,:-1],axis = 1)
X_l = son_veriler.iloc[:,[0,1,2,3,4]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(son_veriler.iloc[:,-1:],X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Mon, 25 Jul 2022   Prob (F-statistic):              0.546
Time:                        10:22:23   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.3

C:\Users\fatih\anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [39]:
x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

In [40]:
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)

In [41]:
y_pred

array([[77.98135142],
       [68.29304916],
       [81.05037539],
       [71.44926132],
       [75.78905304]])

In [42]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86